org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
yarn_mappings=1.21.1+build.3
fabric_version=0.116.15+1.21.1

mod_version=1.0.9
maven_group=com.terminaldetector
archives_base_name=drmd-6dof

junit_version=5.11.3
