-- SCK_GenerateSWEP(config) → complete SWEP .lua string.
-- config = { class, weapon={...}, projectile={...}, flak={...}, guidance={...}, clusters={...} }
-- Writes to DATA/drmd_weapons/generated/<class>.lua and clipboard.

local function Q(s)  return '"' .. tostring(s):gsub('"', '\\"') .. '"' end
local function B(v)  return v and "true" or "false" end
local function N(v)  return tostring(tonumber(v) or 0) end

local function BuildSWEPString(config)
	local wep  = config.weapon     or {}
	local proj = config.projectile or {}
	local flak = config.flak       or {}
	local guid = config.guidance   or {}
	local clusters = config.clusters or {}

	local class = config.class or wep.ClassName or "weapon_d6_custom"

	local lines = {}
	local function L(s) lines[#lines + 1] = (s or "") end

	-- Decide damage class from weapon type
	local dmgClass
	if wep.WeaponType == "beam" then dmgClass = "energy"
	elseif wep.WeaponType == "hitscan" then dmgClass = "kinetic"
	else dmgClass = "kinetic" end

	-- Header
	L("-- Generated by DRMD Weapon Workshop (SCK)")
	L("-- Class: " .. class)
	L("-- DO NOT EDIT — regenerate via SCK editor.")
	L("")
	L("AddCSLuaFile()")
	L("")

	-- SWEP metadata
	L("SWEP.PrintName      = " .. Q(wep.PrintName   or "Custom Weapon"))
	L("SWEP.Author         = \"DRMD Weapon Workshop\"")
	L("SWEP.Category       = " .. Q(wep.Category    or "Primary"))
	L("SWEP.Spawnable      = true")
	L("SWEP.AdminSpawnable = true")
	L("SWEP.Slot           = 2")
	L("SWEP.SlotPos        = 0")
	L("SWEP.HoldType       = \"pistol\"")
	L("SWEP.ViewModel      = \"models/weapons/v_pistol.mdl\"")
	L("SWEP.WorldModel     = \"models/weapons/w_pistol.mdl\"")
	L("SWEP.DrawCrosshair  = false")
	L("SWEP.Primary.Ammo          = " .. Q(wep.AmmoType or "energy"))
	L("SWEP.Primary.ClipSize      = -1")
	L("SWEP.Primary.DefaultClip   = -1")
	L("SWEP.Primary.Automatic     = false")
	L("SWEP.Secondary.Ammo        = \"\"")
	L("SWEP.Secondary.ClipSize    = -1")
	L("SWEP.Secondary.DefaultClip = -1")
	L("SWEP.Secondary.Automatic   = false")
	L("")

	-- Runtime constants
	L("local ENERGY_COST  = " .. N(wep.EnergyCost     or 10))
	L("local FIRE_RATE    = " .. N(wep.FireRate        or 0.5))
	L("local DIRECT_DMG   = " .. N(wep.Damage          or 50))
	L("local SPLASH_DMG   = " .. N(wep.Damage          or 50))
	L("local SPLASH_RAD   = " .. N(wep.SplashRadius    or 0))
	L("local PROJ_SPEED   = " .. N(proj.InitialVelocity or 3000))
	L("local PROJ_SCALE   = " .. N(proj.Scale          or 1))
	L("local PROJ_MASS    = " .. N(proj.Mass           or 5))
	L("local PROJ_LIFE    = " .. N(proj.Lifetime       or 5))
	L("local RECOIL       = 20")
	L("local FIRE_MODE     = " .. Q(proj.FireMode      or "single"))
	L("local BURST_COUNT   = " .. N(proj.BurstCount    or 3))
	L("local BURST_DELAY   = " .. N(proj.BurstDelay    or 0.08))
	L("local VOLLEY_COUNT  = " .. N(proj.VolleyCount   or 3))
	L("local VOLLEY_SPREAD = " .. N(proj.VolleySpread  or 6))
	L("local MUZZLE_IDX    = " .. N(proj.MuzzleIndex   or 0))
	L("")

	-- WeaponClusters block (if any)
	if next(clusters) then
		local ct = SCK_GetClustersText and SCK_GetClustersText(clusters) or ""
		if ct ~= "" then
			L(ct)
			L("")
		end
	end

	-- Initialize
	L("function SWEP:Initialize()")
	L("    self:SetWeaponHoldType(self.HoldType)")
	L("end")
	L("")

	-- PrimaryAttack
	L("function SWEP:PrimaryAttack()")
	L("    local owner = self.Owner")
	L("    if not IsValid(owner) then return end")
	L("    self.Weapon:SetNextPrimaryFire(CurTime() + FIRE_RATE)")
	L("    if not SERVER then return end")
	L("    if D6_Energy and not D6_Energy.TryConsume(owner, \"weapons\", ENERGY_COST) then return end")
	L("")

	if wep.WeaponType == "hitscan" then
		L("    local aimVec = owner:GetAimVector()")
		L("    local startPos = owner:GetShootPos()")
		L("    local tr = util.TraceLine({ start=startPos, endpos=startPos+aimVec*8000, filter=owner })")
		L("    if IsValid(tr.Entity) then")
		L("        D6_Wep.DirectDamage(owner, self.Weapon, tr.Entity, DIRECT_DMG,")
		L("            D6_DAMAGE." .. dmgClass .. ", aimVec * -500)")
		L("    end")
		L("    D6_Wep.ApplyRecoil(owner, aimVec, RECOIL)")
	else
		-- Projectile: прицеливание через D6_Wep.ShootAng (Angle),
		-- точка появления — MuzzleFor при MUZZLE_IDX > 0.
		L("    local ang = D6_Wep.ShootAng(owner)")
		L("    local dir = ang:Forward()")
		L("    local pos")
		L("    if MUZZLE_IDX > 0 and D6_Wep.MuzzleFor then")
		L("        pos = D6_Wep.MuzzleFor(owner, self:GetClass(), MUZZLE_IDX,")
		L("            { fwd = 30, rgt = 0, up = -8 })")
		L("    else")
		L("        pos = owner:GetShootPos() + dir * 30")
		L("    end")
		L("")

		local hasSplash = (tonumber(wep.SplashRadius) or 0) > 0
		L("    local function FireOne(fpos, fdir)")
		L("        D6_Wep.FireProjectile({")
		L("            owner    = owner,")
		L("            pos      = fpos,")
		L("            dir      = fdir,")
		L("            speed    = PROJ_SPEED,")
		L("            model    = " .. Q(proj.Model or "models/weapons/w_crossbow_bolt.mdl") .. ",")
		L("            scale    = PROJ_SCALE,")
		L("            mass     = PROJ_MASS,")
		L("            gravity  = " .. B(proj.Gravity or false) .. ",")
		L("            drag     = " .. B(proj.Drag    or false) .. ",")
		L("            life     = PROJ_LIFE,")
		L("            dmgClass = " .. Q(dmgClass) .. ",")
		L("            inherit  = 1.0,")
		L("            recoil   = RECOIL,")

		if proj.Trail then
			L("            trails   = { { col = Color(200, 200, 255), sw = 20, ew = 0, life = 0.3 } },")
		end

		-- Сигнатура onHit — контракт D6_TrackProjectile (d6_core.lua):
		-- onHit(снаряд, hitEnt, hitPos, hitNormal)
		L("            onHit = function(proj, hitEnt, hitPos, hitNormal)")
		L("                hitPos    = hitPos or (IsValid(proj) and proj:GetPos()) or owner:GetPos()")
		L("                hitNormal = hitNormal or Vector(0, 0, 1)")
		L("                if IsValid(hitEnt) then")
		L("                    D6_Wep.DirectDamage(owner, proj, hitEnt, DIRECT_DMG,")
		L("                        D6_DAMAGE." .. dmgClass .. ", hitNormal * -500)")
		L("                end")
		if hasSplash then
			L("                D6_Wep.SplashDamage(owner, proj, hitPos,")
			L("                    0, SPLASH_DMG, SPLASH_RAD, D6_DAMAGE.explosive, 1, hitEnt)")
		end
		-- Flak on-hit burst
		if (tonumber(flak.FragmentCount) or 0) > 0 then
			L("                -- Flak burst")
			L("                local fcount  = " .. N(flak.FragmentCount or 20))
			L("                local fspeed  = " .. N(flak.FragmentSpeed or 2000))
			L("                local fspread = math.rad(" .. N(flak.SpreadAngle or 30) .. ")")
			L("                local fdmg    = " .. N(flak.FragmentDamage or 10))
			L("                for i = 1, fcount do")
			L("                    local fdir = hitNormal + VectorRand() * math.tan(fspread * 0.5)")
			L("                    D6_Wep.FireProjectile({")
			L("                        owner=owner, pos=hitPos+hitNormal*4, dir=fdir:GetNormalized(),")
			L("                        speed=fspeed, life=0.3, dmgClass=" .. Q(flak.FragmentType or "kinetic") .. ",")
			L("                        model=\"models/weapons/w_crossbow_bolt.mdl\", scale=0.3, mass=0.5,")
			L("                        onHit=function(fp, fe, fhp, fhn)")
			L("                            if IsValid(fe) then")
			L("                                D6_Wep.DirectDamage(owner, fp, fe, fdmg,")
			L("                                    D6_DAMAGE.kinetic, (fhn or Vector(0,0,1)) * -200)")
			L("                            end")
			L("                        end,")
			L("                    })")
			L("                end")
		end
		L("            end,")
		L("        })")
		L("    end")
		L("")

		-- Режимы огня
		L("    if FIRE_MODE == \"burst\" then")
		L("        for i = 0, BURST_COUNT - 1 do")
		L("            timer.Simple(i * BURST_DELAY, function()")
		L("                if not IsValid(owner) or not owner:Alive() then return end")
		L("                local a2 = D6_Wep.ShootAng(owner)")
		L("                local d2 = a2:Forward()")
		L("                local p2")
		L("                if MUZZLE_IDX > 0 and D6_Wep.MuzzleFor then")
		L("                    p2 = D6_Wep.MuzzleFor(owner, " .. Q(class) .. ", MUZZLE_IDX,")
		L("                        { fwd = 30, rgt = 0, up = -8 })")
		L("                else")
		L("                    p2 = owner:GetShootPos() + d2 * 30")
		L("                end")
		L("                FireOne(p2, d2)")
		L("            end)")
		L("        end")
		L("    elseif FIRE_MODE == \"volley\" then")
		L("        local half = (VOLLEY_COUNT - 1) * 0.5")
		L("        for i = 0, VOLLEY_COUNT - 1 do")
		L("            local a2 = Angle(ang.p, ang.y, ang.r)")
		L("            a2:RotateAroundAxis(a2:Up(), (i - half) * VOLLEY_SPREAD)")
		L("            FireOne(pos, a2:Forward())")
		L("        end")
		L("    else")
		L("        FireOne(pos, dir)")
		L("    end")
	end

	L("end")
	L("")

	-- SecondaryAttack stub
	L("function SWEP:SecondaryAttack()")
	L("    self.Weapon:SetNextSecondaryFire(CurTime() + 0.2)")
	L("end")
	L("")

	-- HUD
	L("function SWEP:HUDPaintBackground()")
	L("    if not D6_Wep then return end")
	L("    D6_Wep.DrawEnergyHUD(self.Owner, " .. Q(wep.PrintName or "CUSTOM") .. ", Color(140, 190, 255))")
	L("end")
	L("")

	-- SetupDataTables stub (required)
	L("function SWEP:SetupDataTables() end")
	L("")

	-- SCK_Config opt-in comment
	L("-- SCK_Config opt-in: if present, live config overrides the constants above.")
	L("-- Migrate: replace ENERGY_COST with D6_Wep.Cfg(" .. Q(class) .. ", \"weapon\", \"EnergyCost\", ENERGY_COST)")

	return table.concat(lines, "\n")
end

function SCK_GenerateSWEP(config)
	local code  = BuildSWEPString(config)
	local class = config.class or (config.weapon and config.weapon.ClassName) or "weapon_d6_custom"

	-- Write to DATA
	local dir = "drmd_weapons/generated"
	if not file.IsDir("drmd_weapons", "DATA") then file.CreateDir("drmd_weapons") end
	if not file.IsDir(dir, "DATA")            then file.CreateDir(dir)            end
	file.Write(dir .. "/" .. class .. ".lua", code)

	-- Clipboard
	SetClipboardText(code)

	return code
end
