-- SCK_GenerateSWEP(config) → complete SWEP .lua string.
-- config = { class, weapon={...}, projectile={...}, flak={...}, guidance={...}, clusters={...} }
-- Writes to DATA/drmd_weapons/generated/<class>.lua and clipboard.

local function Q(s)  return '"' .. tostring(s):gsub('"', '\\"') .. '"' end
local function B(v)  return v and "true" or "false" end
local function N(v)  return tostring(tonumber(v) or 0) end

local function BuildSWEPString(config)
	local wep  = config.weapon     or {}
	local proj = config.projectile or {}
	local flak = config.flak       or {}
	local guid = config.guidance   or {}
	local clusters = config.clusters or {}

	local class = config.class or wep.ClassName or "weapon_d6_custom"

	local lines = {}
	local function L(s) lines[#lines + 1] = (s or "") end

	-- Decide damage class from weapon type
	local dmgClass
	if wep.WeaponType == "beam" then dmgClass = "energy"
	elseif wep.WeaponType == "hitscan" then dmgClass = "kinetic"
	else dmgClass = "kinetic" end

	-- Header
	L("-- Generated by DRMD Weapon Workshop (SCK)")
	L("-- Class: " .. class)
	L("-- DO NOT EDIT — regenerate via SCK editor.")
	L("")
	L("AddCSLuaFile()")
	L("")

	-- SWEP metadata
	L("SWEP.PrintName      = " .. Q(wep.PrintName   or "Custom Weapon"))
	L("SWEP.Author         = \"DRMD Weapon Workshop\"")
	L("SWEP.Category       = " .. Q(wep.Category    or "Primary"))
	L("SWEP.Spawnable      = true")
	L("SWEP.AdminSpawnable = true")
	L("SWEP.Slot           = 2")
	L("SWEP.SlotPos        = 0")
	L("SWEP.HoldType       = \"pistol\"")
	L("SWEP.ViewModel      = \"models/weapons/v_pistol.mdl\"")
	L("SWEP.WorldModel     = \"models/weapons/w_pistol.mdl\"")
	L("SWEP.DrawCrosshair  = false")
	L("SWEP.Primary.Ammo          = " .. Q(wep.AmmoType or "energy"))
	L("SWEP.Primary.ClipSize      = -1")
	L("SWEP.Primary.DefaultClip   = -1")
	L("SWEP.Primary.Automatic     = false")
	L("SWEP.Secondary.Ammo        = \"\"")
	L("SWEP.Secondary.ClipSize    = -1")
	L("SWEP.Secondary.DefaultClip = -1")
	L("SWEP.Secondary.Automatic   = false")
	L("")

	-- Runtime constants
	L("local ENERGY_COST  = " .. N(wep.EnergyCost     or 10))
	L("local FIRE_RATE    = " .. N(wep.FireRate        or 0.5))
	L("local DIRECT_DMG   = " .. N(wep.Damage          or 50))
	L("local SPLASH_DMG   = " .. N(wep.Damage          or 50))
	L("local SPLASH_RAD   = " .. N(wep.SplashRadius    or 0))
	L("local PROJ_SPEED   = " .. N(proj.InitialVelocity or 3000))
	L("local PROJ_SCALE   = " .. N(proj.Scale          or 1))
	L("local PROJ_MASS    = " .. N(proj.Mass           or 5))
	L("local PROJ_LIFE    = " .. N(proj.Lifetime       or 5))
	L("local RECOIL       = 20")
	L("")

	-- WeaponClusters block (if any)
	if next(clusters) then
		local ct = SCK_GetClustersText and SCK_GetClustersText(clusters) or ""
		if ct ~= "" then
			L(ct)
			L("")
		end
	end

	-- Initialize
	L("function SWEP:Initialize()")
	L("    self:SetWeaponHoldType(self.HoldType)")
	L("end")
	L("")

	-- PrimaryAttack
	L("function SWEP:PrimaryAttack()")
	L("    local owner = self.Owner")
	L("    if not IsValid(owner) then return end")
	L("    self.Weapon:SetNextPrimaryFire(CurTime() + FIRE_RATE)")
	L("    if not SERVER then return end")
	L("    if D6_Energy and not D6_Energy.TryConsume(owner, \"weapons\", ENERGY_COST) then return end")
	L("")

	if wep.WeaponType == "hitscan" then
		L("    local aimVec = owner:GetAimVector()")
		L("    local startPos = owner:GetShootPos()")
		L("    local tr = util.TraceLine({ start=startPos, endpos=startPos+aimVec*8000, filter=owner })")
		L("    if IsValid(tr.Entity) then")
		L("        D6_Wep.DirectDamage(owner, self.Weapon, tr.Entity, DIRECT_DMG,")
		L("            D6_DAMAGE." .. dmgClass .. ", aimVec * -500)")
		L("    end")
	else
		-- Projectile
		L("    local pos, dir = D6_Wep.ShootAng(owner)")
		L("    D6_Wep.FireProjectile({")
		L("        owner    = owner,")
		L("        pos      = pos,")
		L("        dir      = dir,")
		L("        speed    = PROJ_SPEED,")
		L("        model    = " .. Q(proj.Model or "models/weapons/w_crossbow_bolt.mdl") .. ",")
		L("        scale    = PROJ_SCALE,")
		L("        mass     = PROJ_MASS,")
		L("        gravity  = " .. B(proj.Gravity or false) .. ",")
		L("        drag     = " .. B(proj.Drag    or false) .. ",")
		L("        life     = PROJ_LIFE,")
		L("        dmgClass = " .. Q(dmgClass) .. ",")
		L("        inherit  = true,")
		L("        recoil   = RECOIL,")

		if proj.Trail then
			L("        trails   = { { Color(200, 200, 255), 20, 0, 0.3 } },")
		end

		local hasSplash = (tonumber(wep.SplashRadius) or 0) > 0
		L("        onHit = function(ent, attacker, inflictor, hitPos, hitNormal)")
		L("            D6_Wep.DirectDamage(attacker, inflictor, ent, DIRECT_DMG,")
		L("                D6_DAMAGE." .. dmgClass .. ", hitNormal * -500)")
		if hasSplash then
			L("            D6_Wep.SplashDamage(attacker, inflictor, hitPos,")
			L("                0, SPLASH_DMG, SPLASH_RAD, D6_DAMAGE.explosive, 1, ent)")
		end
		-- Flak on-hit burst
		if (tonumber(flak.FragmentCount) or 0) > 0 then
			L("            -- Flak burst")
			L("            local fcount = " .. N(flak.FragmentCount or 20))
			L("            local fspeed = " .. N(flak.FragmentSpeed or 2000))
			L("            local fspread = math.rad(" .. N(flak.SpreadAngle or 30) .. ")")
			L("            local fdmg = " .. N(flak.FragmentDamage or 10))
			L("            for i = 1, fcount do")
			L("                local fdir = hitNormal + VectorRand() * math.tan(fspread * 0.5)")
			L("                D6_Wep.FireProjectile({")
			L("                    owner=attacker, pos=hitPos+hitNormal*4, dir=fdir:GetNormalized(),")
			L("                    speed=fspeed, life=0.3, dmgClass=" .. Q(flak.FragmentType or "kinetic") .. ",")
			L("                    model=\"models/weapons/w_crossbow_bolt.mdl\", scale=0.3, mass=0.5,")
			L("                    onHit=function(e,a,i,p,n) D6_Wep.DirectDamage(a,i,e,fdmg,D6_DAMAGE.kinetic,n*-200) end,")
			L("                })")
			L("            end")
		end
		L("        end,")
		L("    })")
	end

	-- Recoil
	L("    D6_Wep.ApplyRecoil(owner, owner:GetAimVector() * -1, RECOIL)")
	L("end")
	L("")

	-- SecondaryAttack stub
	L("function SWEP:SecondaryAttack()")
	L("    self.Weapon:SetNextSecondaryFire(CurTime() + 0.2)")
	L("end")
	L("")

	-- HUD
	L("function SWEP:HUDPaintBackground()")
	L("    if not D6_Wep then return end")
	L("    D6_Wep.DrawEnergyHUD(self.Owner, " .. Q(wep.PrintName or "CUSTOM") .. ", Color(140, 190, 255))")
	L("end")
	L("")

	-- SetupDataTables stub (required)
	L("function SWEP:SetupDataTables() end")
	L("")

	-- SCK_Config opt-in comment
	L("-- SCK_Config opt-in: if present, live config overrides the constants above.")
	L("-- Migrate: replace ENERGY_COST with D6_Wep.Cfg(" .. Q(class) .. ", \"weapon\", \"EnergyCost\", ENERGY_COST)")

	return table.concat(lines, "\n")
end

function SCK_GenerateSWEP(config)
	local code  = BuildSWEPString(config)
	local class = config.class or (config.weapon and config.weapon.ClassName) or "weapon_d6_custom"

	-- Write to DATA
	local dir = "drmd_weapons/generated"
	if not file.IsDir("drmd_weapons", "DATA") then file.CreateDir("drmd_weapons") end
	if not file.IsDir(dir, "DATA")            then file.CreateDir(dir)            end
	file.Write(dir .. "/" .. class .. ".lua", code)

	-- Clipboard
	SetClipboardText(code)

	return code
end
