package com.terminaldetector.drmd.workshop;

/**
 * Code generator — port of SCK generator.lua.
 * Emits WeaponDef stub + WeaponClusters construction block.
 */
public final class CodeGenerator {
	private CodeGenerator() {}

	public static String generateJava(WeaponConfig cfg) {
		String name = String.valueOf(cfg.weapon.getOrDefault("PrintName", "Custom"));
		String className = String.valueOf(cfg.weapon.getOrDefault("ClassName", "weapon_d6_custom"))
				.replace("weapon_d6_", "").replaceAll("[^a-zA-Z0-9_]", "_");
		float damage = toFloat(cfg.weapon.get("Damage"));
		float rate = toFloat(cfg.weapon.get("FireRate"));
		float energy = toFloat(cfg.weapon.get("EnergyCost"));
		float splash = toFloat(cfg.weapon.get("SplashRadius"));
		float speed = toFloat(cfg.projectile.get("InitialVelocity"));
		boolean homing = Boolean.TRUE.equals(cfg.projectile.get("Homing"));
		int frags = (int) toFloat(cfg.flak.get("FragmentCount"));

		StringBuilder sb = new StringBuilder();
		sb.append("// Generated by DRMD Weapon Workshop\n");
		sb.append("// Class: weapon_d6_").append(className).append("\n");
		sb.append("// Target: ").append(cfg.targetWeaponId).append("\n");
		sb.append("// DO NOT EDIT — regenerate via Workshop.\n\n");
		sb.append("WeaponDef def = new WeaponDef(\n");
		sb.append("    \"").append(className).append("\",\n");
		sb.append("    \"").append(name).append("\",\n");
		sb.append("    \"").append(cfg.weapon.get("Category")).append("\",\n");
		sb.append("    ").append(energy).append("f, ").append(rate).append("f,\n");
		sb.append("    ").append(damage).append("f, ")
				.append(toFloat(cfg.projectile.get("ExplosionDamage"))).append("f, ")
				.append(splash > 0 ? splash : toFloat(cfg.projectile.get("ExplosionRadius"))).append("f,\n");
		sb.append("    ").append(speed).append("f, 40f,\n");
		sb.append("    DamageClass.KINETIC, \"")
				.append(homing ? "homing" : (frags > 0 ? "flak" : "basic")).append("\"\n");
		sb.append(");\n\n");

		sb.append("// WeaponClusters construction (Center→Upper→SideLeft→SideRight→Lower)\n");
		sb.append("java.util.List<ClusterModule> clusters = new java.util.ArrayList<>();\n");
		WeaponClusters.sort(cfg.clusters);
		for (ClusterModule m : cfg.clusters) {
			sb.append("clusters.add(WeaponClusters.make(\"")
					.append(m.cluster).append("\", ").append(m.slot).append(", \"")
					.append(m.name).append("\", \"").append(m.model).append("\", ")
					.append(m.posFwd).append("f, ").append(m.posRgt).append("f, ").append(m.posUp).append("f, ")
					.append(m.scaleX).append("f, ").append(m.muzzle).append(", ").append(m.muzzleIdx)
					.append("));\n");
		}
		sb.append("ConstructionRegistry.setOverride(\"").append(cfg.targetWeaponId)
				.append("\", clusters);\n");

		if (frags > 0) {
			sb.append("// Flak fragments: ").append(frags)
					.append(" @ ").append(cfg.flak.get("SpreadAngle")).append("°\n");
		}
		if (homing) {
			sb.append("// Guidance: ").append(cfg.guidance.get("GuidanceType")).append("\n");
		}
		int muzzles = WeaponClusters.extractMuzzles(cfg.clusters).size();
		sb.append("// Muzzles: ").append(muzzles).append("\n");
		return sb.toString();
	}

	private static float toFloat(Object o) {
		if (o instanceof Number n) return n.floatValue();
		try { return Float.parseFloat(String.valueOf(o)); } catch (Exception e) { return 0f; }
	}
}
